### ISSUE TITLE
Usage with two-legged OAuth

### ISSUE THREAD

**Issue by dotboris** [MaxCDN/maxcli#14]
According to MaxCDN's API doc (https://docs.maxcdn.com/), you can use two-legged OAuth to talk to the api.

> The MaxCDN RWS supports both 2-legged and 3-legged authentication.

The doc explains how to use two-legged OAuth:

> 2-legged OAuth describes a typical client-server scenario, without any user involvement. On a conceptual level 2-legged OAuth simply consists of the first and last steps of 3-legged OAuth:
> - Client has signed up to the server and received their client credentials (also known as “consumer key and secret”)
> - Client uses their client credentials (and **empty token credentials**) to access the protected resources on the server

This leads me to believe that I can use the maxcli tool with two-legged OAuth since it talks to the api.

The doc for maxcli states that I need 3 things: alias, token and secret.

My understanding is that the alias is my company alias, the token is a oauth consumer secret and that the token is the consumer token (which should be empty according to the API docs).

I've tried using my alias, secret and empty token, but it's not working. I think that this is because the commands check that the token is not an empty string.

How do I use these tools? Where do I get the alias, token and secret?

**Comment by jmervine** [comment]
MaxCLI do require a valid alias, token and secret. You should be able to obtain those from the MaxCDN Consumer Panel's API section, [here](https://cp.maxcdn.com/account/api). For more questions or issues, contact MaxCDN directly at support@maxcdn.com.

Cheers!
