### ISSUE TITLE
invalid signature when using maxpurge

### ISSUE THREAD

**Issue by ondreian** [MaxCDN/maxcli#15]
Since around a week ago, I started seeing this on my CD deploys, I thought perhaps there was just an issue that would correct itself in a day or so, but it's still happening.

```
[madcdn] >>> purging /builds/edge/<some asset>.js
: Invalid signature

Purge failed after 98.198724ms.

./scripts/deploy edge returned exit code 2

Action failed: ./scripts/deploy edge
```
 Just to see if I could reproduce it locally, I ran `maxpurge` on my localhost and it has the same `: Invalid signature` error output.

I rotated my credentials just in case there was some reason they were expired/revoked, but even with the new credentials it's the same story.

Did something change internally that wasn't accounted for here? For now I just am logging into the admin panel to purge the files.

**Comment by rogerlightfoot** [comment]
We are getting the same issue. Did you manage to fix this?

**Comment by ondreian** [comment]
I have not managed to fix it, nor have I heard a response about it.

**Comment by rogerlightfoot** [comment]
We are in contact with MaxCDN support. I'll let you know if and when I have a resolution. This is potentially a deal-breaker for us.

**Comment by jmervine** [comment]
@ondreian @rogerlightfoot I'll take a look and see if I can find a quick fix. Otherwise, please post here what you hear from Max's support.

Cheers!

**Comment by jmervine** [comment]
@ondreian @rogerlightfoot Please confirm that you're still seeing these issues...

```
Purge successful after: 3.969191319s.
```

Cheers!

**Comment by jmervine** [comment]
Also, please verify your version...

```
maxpurge version 1.0.4
```

**Comment by ondreian** [comment]
Appreciate you taking a look.

still seems to be happening for me:

```bash
maxpurge -v
maxpurge version 1.0.4
```
example:
```
maxpurge -z <zone> --file <file> -a $MAXCDN_ALIAS -t $MAXCDN_CONSUMER_KEY -s $MAXCDN_CONSUMER_SECRET
: Invalid signature

Purge failed after 264.804229ms.

**Comment by jmervine** [comment]
Okay, I seem to be getting the same error with a single file purge. Let me continue to dig in and see what I can find.

**Comment by jmervine** [comment]
In the mean time, as a workaround, you should be able curl an individual file like so do purge it...

```
curl  -sI https://<cdn domain>/purge/<file path>
```

Not sure if that helps?

**Comment by jmervine** [comment]
The issue appears to be [here](https://github.com/MaxCDN/go-maxcdn/blob/master/maxcdn.go#L157). The API is now expecting `files` and not `file`. While not a complicated fix, it's going to take a bit for me test and update.

**Comment by jmervine** [comment]
I've updated the core lib to fix this error. You'll need to run `go get -u github.com/maxcdn/maxcli/maxpurge` to rebuild with the update. As the code for `maxpurge` itself didn't change, there's no version bump and I have yet to rebuild the binaries. I'm going to leave this open until that's done.

**Comment by ondreian** [comment]
much appreciated on getting this resolved @jmervine

**Comment by jmervine** [comment]
For sure, mind confirming if all is working correctly for you.

**Comment by rogerlightfoot** [comment]
@jmervine Thank you very much for looking into this. Your tools have been so helpful for us. I'm in the UK and unable to test this from home at the moment. Also, I will need the Windows executables but have no idea how to create these. Are you planning on rebuilding these please?

**Comment by jmervine** [comment]
@rogerlightfoot Glad to hear the tools are helpful. I was not planning on cross compiling at this time. The process has changed quite a bit since I last looked at this and I'm going to need to spend some time getting the process updated. 

In the mean time, you should be able to get the golang windows install here -- https://golang.org/dl/. I haven't worked on Windows in quite some time, but on a quick search, this link -- http://www.wadewegner.com/2014/12/easy-go-programming-setup-for-windows/ -- looks like it'll run you through getting setup real quick.

I'll post here again any updates to build versions for Windows, Mac and the other OSs.

Cheers!

**Comment by rogerlightfoot** [comment]
@jmervine Thanks very much for that. I'll give it a try.

**Comment by jmervine** [comment]
@rogerlightfoot To cross compile for windows on either mac or linux you should be able to do the following (on go 1.5 and up)...

```
env GOOS=windows GOARCH=amd64 go build -o maxpurge.exe github.com/MaxCDN/maxcli/maxpurge
```

That said, I'm hoping to have binaries for windows, mac and linux available some time tomorrow.

**Comment by rogerlightfoot** [comment]
@jmervine That would be fantastic - thanks!

**Comment by jmervine** [comment]
@rogerlightfoot et al --

Updated binaries are now linked to from the README. `maxpurge` should now be version 1.0.5. I'm going to close this issue. Please let me know if you have any additional issues.

Cheers!

**Comment by rogerlightfoot** [comment]
@jmervine the new binaries are working. You are a top man -- thank you so much.

**Comment by ondreian** [comment]
same, works for me. thanks again.
